In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("car_data.csv")

df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [3]:
df.shape

(4340, 8)

In [4]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='str')

In [5]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(763)

In [7]:
df = df.drop_duplicates()

df.shape

(3577, 8)

In [8]:
df['brand'] = df['name'].str.split().str[0]

df[['name', 'brand']].head()

                       name    brand
0             Maruti 800 AC   Maruti
1  Maruti Wagon R LXI Minor   Maruti
2      Hyundai Verna 1.6 SX  Hyundai
3    Datsun RediGO T Option   Datsun
4     Honda Amaze VX i-DTEC    Honda

In [9]:
df['model'] = df['name'].str.split().str[1:].str.join(' ')

df[['name', 'brand', 'model']].head()

                       name    brand              model
0             Maruti 800 AC   Maruti             800 AC
1  Maruti Wagon R LXI Minor   Maruti  Wagon R LXI Minor
2      Hyundai Verna 1.6 SX  Hyundai       Verna 1.6 SX
3    Datsun RediGO T Option   Datsun    RediGO T Option
4     Honda Amaze VX i-DTEC    Honda    Amaze VX i-DTEC

In [10]:
df = df.drop(columns=['name'])

df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand,model
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,Maruti,800 AC
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,Maruti,Wagon R LXI Minor
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,Hyundai,Verna 1.6 SX
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,Datsun,RediGO T Option
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,Honda,Amaze VX i-DTEC

In [11]:
df[['brand', 'model', 'fuel', 'seller_type', 'transmission', 'owner']].nunique()

brand             29
model           1491
fuel               5
seller_type        3
transmission       2
owner              5
dtype: int64

In [12]:
df = pd.get_dummies(
    df,
    columns=[
        'brand',
        'model',
        'fuel',
        'seller_type',
        'transmission',
        'owner'
    ],
    drop_first=True
)

df.head()

,year,selling_price,km_driven,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,...,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2007,60000,70000,False,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False
1,2007,135000,50000,False,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False
2,2012,600000,100000,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
3,2017,250000,46000,False,False,False,False,True,False,False,...,False,False,True,True,False,True,False,False,False,False
4,2014,450000,141000,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,True,False,False

In [13]:
X = df.drop(columns=['selling_price'])
y = df['selling_price']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (3577, 1531)
y shape: (3577,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (2861, 1531)
X_test: (716, 1531)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

print("Scaling completed")

Scaling completed

In [16]:
from sklearn.linear_model import LinearRegression

model_lr = LinearRegression()

model_lr.fit(X_train_sc, y_train)

y_pred_lr = model_lr.predict(X_test_sc)

print("Linear Regression completed")

Linear Regression completed

In [17]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
mae_lr = mean_absolute_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression")
print("RMSE:", rmse_lr)
print("MAE:", mae_lr)
print("R2 Score:", r2_lr)

Linear Regression
RMSE: 368545.5035667431
MAE: 128596.27505863894
R2 Score: 0.5783554037401173

In [18]:
from sklearn.linear_model import Ridge

model_ridge = Ridge(alpha=1.0)

model_ridge.fit(X_train_sc, y_train)

y_pred_ridge = model_ridge.predict(X_test_sc)

rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("Ridge Regression")
print("RMSE:", rmse_ridge)
print("MAE:", mae_ridge)
print("R2 Score:", r2_ridge)

Ridge Regression
RMSE: 368572.9857615879
MAE: 128594.96904279848
R2 Score: 0.5782925178772764

In [19]:
from sklearn.neighbors import KNeighborsRegressor

model_knn = KNeighborsRegressor(n_neighbors=5)

model_knn.fit(X_train_sc, y_train)

y_pred_knn = model_knn.predict(X_test_sc)

rmse_knn = np.sqrt(mean_squared_error(y_test, y_pred_knn))
mae_knn = mean_absolute_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print("KNN Regression")
print("RMSE:", rmse_knn)
print("MAE:", mae_knn)
print("R2 Score:", r2_knn)

KNN Regression
RMSE: 491385.53251081303
MAE: 191002.20530726257
R2 Score: 0.2504354541707884

In [20]:
from sklearn.tree import DecisionTreeRegressor

model_dt = DecisionTreeRegressor(random_state=42)

model_dt.fit(X_train_sc, y_train)

y_pred_dt = model_dt.predict(X_test_sc)

rmse_dt = np.sqrt(mean_squared_error(y_test, y_pred_dt))
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Regression")
print("RMSE:", rmse_dt)
print("MAE:", mae_dt)
print("R2 Score:", r2_dt)

Decision Tree Regression
RMSE: 392144.7991961993
MAE: 157041.7590782123
R2 Score: 0.5226276900877278

In [21]:
from sklearn.ensemble import RandomForestRegressor

model_rf = RandomForestRegressor(
    random_state=42
)

model_rf.fit(X_train_sc, y_train)

y_pred_rf = model_rf.predict(X_test_sc)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Regression")
print("RMSE:", rmse_rf)
print("MAE:", mae_rf)
print("R2 Score:", r2_rf)

Random Forest Regression
RMSE: 358155.1740649948
MAE: 136142.39959233397
R2 Score: 0.6017949494571321

In [22]:
results = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'Ridge Regression',
        'KNN Regression',
        'Decision Tree',
        'Random Forest'
    ],
    'RMSE': [
        rmse_lr,
        rmse_ridge,
        rmse_knn,
        rmse_dt,
        rmse_rf
    ],
    'MAE': [
        mae_lr,
        mae_ridge,
        mae_knn,
        mae_dt,
        mae_rf
    ],
    'R2 Score': [
        r2_lr,
        r2_ridge,
        r2_knn,
        r2_dt,
        r2_rf
    ]
})

results.sort_values('RMSE')

               Model           RMSE            MAE  R2 Score
4      Random Forest  358155.174065  136142.399592  0.601795
0  Linear Regression  368545.503567  128596.275059  0.578355
1   Ridge Regression  368572.985762  128594.969043  0.578293
3      Decision Tree  392144.799196  157041.759078  0.522628
2     KNN Regression  491385.532511  191002.205307  0.250435

In [ ]:
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}

grid = GridSearchCV(
    RandomForestRegressor(random_state=42),
    params,
    cv=5,
    scoring='r2'
)

grid.fit(X_train_sc, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV R2 Score:", grid.best_score_)

In [ ]:
best_model = grid.best_estimator_

y_pred_best = best_model.predict(X_test_sc)

rmse_best = np.sqrt(mean_squared_error(y_test, y_pred_best))
mae_best = mean_absolute_error(y_test, y_pred_best)
r2_best = r2_score(y_test, y_pred_best)

print("Tuned Random Forest")
print("RMSE:", rmse_best)
print("MAE:", mae_best)
print("R2 Score:", r2_best)

In [ ]:
df_cluster = pd.read_csv("car_data.csv")

df_cluster = df_cluster[
    [
        'year',
        'km_driven',
        'fuel',
        'seller_type',
        'transmission',
        'owner',
        'selling_price'
    ]
]

df_cluster.head()

In [ ]:
df_cluster = pd.get_dummies(
    df_cluster,
    columns=[
        'fuel',
        'seller_type',
        'transmission',
        'owner'
    ],
    drop_first=True
)

df_cluster.head()

In [ ]:
X_cluster = df_cluster.drop(columns=['selling_price'])

print("Cluster features shape:", X_cluster.shape)

In [ ]:
scaler_cluster = StandardScaler()

X_cluster_sc = scaler_cluster.fit_transform(X_cluster)

print("K-Means scaling completed")

In [ ]:
from sklearn.cluster import KMeans

inertia = []

for k in range(2, 8):
    kmeans = KMeans(
        n_clusters=k,
        init='k-means++',
        random_state=42
    )
    kmeans.fit(X_cluster_sc)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(range(2, 8), inertia, marker='o')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

In [ ]:
kmeans = KMeans(
    n_clusters=3,
    init='k-means++',
    random_state=42
)

kmeans.fit(X_cluster_sc)

df_cluster['cluster'] = kmeans.labels_

df_cluster['cluster'].value_counts()

In [ ]:
cluster_price = df_cluster.groupby('cluster')['selling_price'].mean()

cluster_price.sort_values()

In [ ]:
cluster_order = cluster_price.sort_values().index

cluster_names = {
    cluster_order[0]: 'Budget',
    cluster_order[1]: 'Mid-Range',
    cluster_order[2]: 'Premium'
}

df_cluster['market_segment'] = df_cluster['cluster'].map(cluster_names)

df_cluster[['cluster', 'market_segment', 'selling_price']].head()

In [ ]:
cluster_summary = df_cluster.groupby('market_segment').agg({
    'year': 'mean',
    'km_driven': 'mean',
    'selling_price': 'mean'
}).round(2)

cluster_summary

In [ ]:
from sklearn.metrics import silhouette_score

silhouette = silhouette_score(
    X_cluster_sc,
    df_cluster['cluster']
)

print("Silhouette Score:", silhouette)

In [ ]:
results_final = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'Ridge Regression',
        'KNN Regression',
        'Decision Tree',
        'Random Forest',
        'Tuned Random Forest'
    ],
    'RMSE': [
        rmse_lr,
        rmse_ridge,
        rmse_knn,
        rmse_dt,
        rmse_rf,
        rmse_best
    ],
    'MAE': [
        mae_lr,
        mae_ridge,
        mae_knn,
        mae_dt,
        mae_rf,
        mae_best
    ],
    'R2 Score': [
        r2_lr,
        r2_ridge,
        r2_knn,
        r2_dt,
        r2_rf,
        r2_best
    ]
})

results_final.sort_values('RMSE')

In [ ]:
plt.figure(figsize=(8, 5))

plt.scatter(y_test, y_pred_best, alpha=0.5)

plt.xlabel('Actual Selling Price')
plt.ylabel('Predicted Selling Price')
plt.title('Actual vs Predicted Car Price')

plt.show()

In [ ]:
X_train_ann = np.array(X_train_sc)
X_test_ann = np.array(X_test_sc)

y_train_ann = np.array(y_train).reshape(-1, 1)
y_test_ann = np.array(y_test).reshape(-1, 1)

y_mean = y_train_ann.mean()
y_std = y_train_ann.std()

y_train_sc = (y_train_ann - y_mean) / y_std

print("ANN data prepared")
print("Input shape:", X_train_ann.shape)

In [ ]:
input_size = X_train_ann.shape[1]
hidden_size = 10
output_size = 1

np.random.seed(42)

W1 = np.random.randn(input_size, hidden_size) * 0.01
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size) * 0.01
b2 = np.zeros((1, output_size))

print("Input size:", input_size)
print("Hidden size:", hidden_size)
print("Output size:", output_size)

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

print("Sigmoid function ready")

In [ ]:
def forward(X):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    y_pred = z2

    return z1, a1, y_pred

print("Forward propagation ready")

In [ ]:
learning_rate = 0.01
epochs = 1000

for i in range(epochs):
    z1, a1, y_pred = forward(X_train_ann)

    loss = np.mean((y_train_sc - y_pred) ** 2)

    dz2 = 2 * (y_pred - y_train_sc) / len(X_train_ann)
    dW2 = np.dot(a1.T, dz2)
    db2 = np.sum(dz2, axis=0, keepdims=True)

    da1 = np.dot(dz2, W2.T)
    dz1 = da1 * a1 * (1 - a1)

    dW1 = np.dot(X_train_ann.T, dz1)
    db1 = np.sum(dz1, axis=0, keepdims=True)

    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1

print("ANN training completed")
print("Final Loss:", loss)

In [ ]:
z1_test, a1_test, ypred_ann_sc = forward(X_test_ann)

ypred_ann = (ypred_ann_sc * y_std) + y_mean

print("ANN prediction completed")
print("Prediction shape:", ypred_ann.shape)

In [ ]:
rmse_ann = np.sqrt(mean_squared_error(y_test, ypred_ann))
mae_ann = mean_absolute_error(y_test, ypred_ann)
r2_ann = r2_score(y_test, ypred_ann)

print("ANN Regression")
print("RMSE:", rmse_ann)
print("MAE:", mae_ann)
print("R2 Score:", r2_ann)

In [ ]:
results_final = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'Ridge Regression',
        'KNN Regression',
        'Decision Tree',
        'Random Forest',
        'Tuned Random Forest',
        'ANN'
    ],
    'RMSE': [
        rmse_lr,
        rmse_ridge,
        rmse_knn,
        rmse_dt,
        rmse_rf,
        rmse_best,
        rmse_ann
    ],
    'MAE': [
        mae_lr,
        mae_ridge,
        mae_knn,
        mae_dt,
        mae_rf,
        mae_best,
        mae_ann
    ],
    'R2 Score': [
        r2_lr,
        r2_ridge,
        r2_knn,
        r2_dt,
        r2_rf,
        r2_best,
        r2_ann
    ]
})

results_final.sort_values('RMSE')

In [ ]:


import joblib

joblib.dump(best_model, "best_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "feature_columns.pkl")

joblib.dump(kmeans, "kmeans_model.pkl")
joblib.dump(scaler_cluster, "cluster_scaler.pkl")
joblib.dump(cluster_names, "cluster_names.pkl")

print("All models and preprocessing objects saved successfully")

In [ ]:
joblib.dump(
    {
        "W1": W1,
        "b1": b1,
        "W2": W2,
        "b2": b2,
        "y_mean": y_mean,
        "y_std": y_std
    },
    "ann_model.pkl"
)

print("ANN model saved successfully")

In [ ]:
results_final.to_csv("model_results.csv", index=False)

print("Model results saved successfully")

In [ ]:
cluster_summary.to_csv("cluster_summary.csv")

print("Cluster summary saved successfully")

In [ ]:
joblib.dump(
    X_cluster.columns.tolist(),
    "cluster_feature_columns.pkl"
)

print("K-Means feature columns saved successfully")